imports:
  - config.yaml

parameters:
  databricks:
    address: https://westeurope.azuredatabricks.net
    clusterId: '0106-164555-acing965'
    orgId: '776384709737263' # Azure Databricks only
    workspaceBaseDir: '/master-jirka' # change to '/{currentBranch}' to use current branch name as dir name
