image: databricksruntime/standard:6.0.x-scala2.11

variables:
  APP_ENV: test

before_script:
  - apt-get update && apt-get install -y curl gcc git
  - source /databricks/conda/etc/profile.d/conda.sh
  - ./env-init.sh
  - source $HOME/.poetry/env
  - conda activate $PWD/.venv

code_analysis:
  stage: test
  script:
    - ./pylint.sh
    - ./check-crlf.sh

deploy:
  stage: deploy
  when: manual
  script:
    - console dbx:deploy --env=prod
  artifacts:
    paths:
      - $PWD/dist
    expire_in: 30 days
