[tool.poetry]
name = "t__myproject__t"
version = "1.0"
description = "Bricksflow project skelefon"
readme = "README.md"

authors = [
    "Jiri Koutny <jiri.koutny@datasentics.com>"
]

classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]

include = ["*.yaml", "*.json"]

packages = [
    { include = "__myproject__", from = "src" },
]

[tool.poetry.dependencies]
python = "~3.7.3"
databricks-bundle = "^0.6.0"
datalake-bundle = ">=0.5.0a9"

[tool.poetry.dev-dependencies]
pyfony-core = "^0.7.0"
databricks-connect = ">=7.3.7"
dbx-deploy = "^0.13.0"
pylint = "2.4.*"

[pyfony.bootstrap]
rootModuleName = "__myproject__"
