imports:
  - '@databricksbundle/spark/spark_autodetect.yaml'
  - config.yaml

parameters:
  databricks:
    address: https://westeurope.azuredatabricks.net
    token: dapib2946d4e4763446d3e40b086521b0cbf
    clusterId: 0302-161725-budge83
    orgId: 8394585307568385
    projectRoot: '/{currentBranch}'
    createReleases: False
