imports:
  - '@databricksbundle/spark/spark_test.yaml'
  - config.yaml

parameters:
  databricks:
    address: https://westeurope.azuredatabricks.net
    token: ''
    clusterId: ''
    orgId: ''
    projectRoot: '/{currentBranch}'
