imports:
  - '@databricksbundle/spark/spark_autodetect.yaml'
  - config.yaml

parameters:
  databricks:
    address: https://westeurope.azuredatabricks.net
    token: '%env(DBX_TOKEN)%'
    clusterId: '%env(DBX_CLUSTER)%'
    orgId: '%env(DBX_ORG_ID)%'
    workspaceBaseDir: '/master' # change to '/{currentBranch}' to use current branch name as dir name
