parameters:
  myparameter:
    myvalue: 'This is a sample string config value'

  dbxdeploy:
    databricks:
      host: '%databricks.address%'
      user: jiri.koutny@datasentics.com
      token: '%databricks.token%'
      clusterId: '%databricks.clusterId%'
      projectRoot: '%databricks.projectRoot%'
      createReleases: '%databricks.createReleases%'
    notebooks:
      databricksNotebookGlobs: ['myproject/solutions/**/*.py']

  databricksbundle:
    databricksConnect:
      connection:
        address: '%databricks.address%'
        token: '%databricks.token%'
        clusterId: '%databricks.clusterId%'
        orgId: '%databricks.orgId%'
