parameters:
  myparameter:
    myvalue: 'This is a sample string config value'

  dbxdeploy:
    databricks:
      host: '%databricks.address%'
      token: '%databricks.token%'
      clusterId: '%databricks.clusterId%'
      projectRoot: '%databricks.projectRoot%'
    notebooks:
      paths:
        - 'myproject/app/install_master_package.py'
        - 'myproject/solutions/**/*.py'

  databricksbundle:
    databricksConnect:
      connection:
        address: '%databricks.address%'
        token: '%databricks.token%'
        clusterId: '%databricks.clusterId%'
        orgId: '%databricks.orgId%'
        port: 15001
