imports:
  - '@databricksbundle/spark/spark_autodetect.yaml'
  - config.yaml

parameters:
  databricks:
    address: https://westeurope.azuredatabricks.net
    token: '%env(DBX_TOKEN)%'
    clusterId: '%env(DBX_CLUSTER)%'
    orgId: '%env(DBX_ORG_ID)%'
    projectRoot: '/{currentBranch}'
    createReleases: False
