name: pipeline
on: [push]

jobs:
  pipeline:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: conda-incubator/setup-miniconda@v2.0.0
        with:
          miniconda-version: 'py38_4.8.3'
      - name: setup
        run: |
          cp .env.dist .env
          sed -i 's/DBX_TOKEN=/DBX_TOKEN=abcdefgh123456789/g' .env # remove DBX_TOKEN env var from .env
          ./env-init.sh -y --verbose
          eval "$(conda shell.bash hook)"
          source $HOME/.poetry/env
          conda activate $PWD/.venv
      - name: pylint
        run: |
          eval "$(conda shell.bash hook)"
          conda activate $PWD/.venv
          ./pylint.sh
      - name: crlf
        run: |
          eval "$(conda shell.bash hook)"
          conda activate $PWD/.venv
          ./check-crlf.sh
      - name: compare_configs
        run: |
          eval "$(conda shell.bash hook)"
          conda activate $PWD/.venv
          ./compare_configs.py src/__myproject__/_config/config_dev.yaml src/__myproject__/_config/config_prod.yaml
      - name: tests
        run: |
          eval "$(conda shell.bash hook)"
          conda activate $PWD/.venv
          ./run_tests.sh
      - name: containerChecks
        run: |
          eval "$(conda shell.bash hook)"
          conda activate $PWD/.venv
          ~/.poetry/bin/poetry install --no-root --no-dev # remove all dev dependencies
          pip install databricks-connect==6.4.0 # pyspark is still needed
          unset DBX_DEPLOY_ENABLED
          python container_init_dev.py
          python container_init_prod.py
